# Generated by Django 5.2.17 on 2026-09-08 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistgroup',
            name='members',
            field=models.ManyToManyField(related_name='specialist_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routingrule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='routing.specialistgroup'),
        ),
        migrations.AddConstraint(
            model_name='routingrule',
            constraint=models.UniqueConstraint(fields=('category', 'group', 'applicant_type'), name='routing_unique_rule'),
        ),
        migrations.AddConstraint(
            model_name='routingrule',
            constraint=models.CheckConstraint(condition=models.Q(('applicant_type__in', ['student', 'parent', 'teacher'])), name='routing_valid_applicant'),
        ),
    ]
