# Generated by Django 5.2.17 on 2026-09-09 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_policy(apps, schema_editor):
    apps.get_model("routing", "ServicePolicy").objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_initial_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=0)),
                ('return_limit', models.PositiveSmallIntegerField(default=2)),
                ('operator_wait_hours', models.PositiveSmallIntegerField(default=2)),
                ('expert_wait_hours', models.PositiveSmallIntegerField(default=24)),
                ('auto_close_days', models.PositiveSmallIntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=16)),
                ('target', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField(unique=True)),
                ('reason', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(seed_policy, migrations.RunPython.noop),
        migrations.RunSQL(
            """CREATE FUNCTION otklik_immutable_configuration_event() RETURNS trigger
            LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Configuration audit is immutable'; END $$;
            CREATE TRIGGER immutable_configuration_event BEFORE UPDATE OR DELETE ON routing_configurationevent
            FOR EACH ROW EXECUTE FUNCTION otklik_immutable_configuration_event();""",
            """DROP TRIGGER immutable_configuration_event ON routing_configurationevent;
            DROP FUNCTION otklik_immutable_configuration_event();""",
        ),
    ]
