# Generated by Django 5.2.17 on 2026-09-08 15:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applicant_type', models.CharField(choices=[('student', 'Школьник'), ('parent', 'Родитель'), ('teacher', 'Педагог')], max_length=16)),
                ('entry_path', models.CharField(choices=[('category', 'Выбрать ситуацию'), ('story', 'Рассказать своими словами')], max_length=16)),
                ('status', models.CharField(choices=[('new', 'Новое'), ('assigned', 'Распределено'), ('in_progress', 'В работе'), ('needs_info', 'Нужно уточнение'), ('answer_ready', 'Ответ готов'), ('returned', 'Возвращено'), ('completed', 'Завершено'), ('rejected', 'Отклонено'), ('closed_no_response', 'Закрыто без ответа')], default='new', max_length=24)),
                ('priority', models.CharField(choices=[('standard', 'Стандарт'), ('urgent', 'Срочно'), ('low', 'Низкий')], default='standard', max_length=16)),
                ('original_text', models.TextField()),
                ('code_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_crisis', models.BooleanField(default=False)),
                ('return_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='appeal_queue_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['new', 'assigned', 'in_progress', 'needs_info', 'answer_ready', 'returned', 'completed', 'rejected', 'closed_no_response'])), name='appeal_valid_status'), models.CheckConstraint(condition=models.Q(('priority__in', ['standard', 'urgent', 'low'])), name='appeal_valid_priority'), models.CheckConstraint(condition=models.Q(('applicant_type__in', ['student', 'parent', 'teacher'])), name='appeal_valid_applicant'), models.CheckConstraint(condition=models.Q(('entry_path__in', ['category', 'story'])), name='appeal_valid_entry')],
            },
        ),
    ]
