# Generated by Django 5.2.17 on 2026-09-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(max_length=16)),
                ('action', models.CharField(max_length=32)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('priority', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='AppealParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('responsible', 'Ответственный'), ('coexecutor', 'Соисполнитель')], max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppealSession',
            fields=[
                ('token_digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='appeal',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
