# Generated by Django 5.2.17 on 2026-09-08 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_appealevent_appealparticipant_appealsession_and_more'),
        ('routing', '0003_unknown_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='category',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.PROTECT, to='routing.category'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='close_kind',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='appeal',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='last_applicant_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='operator_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='public_resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
