# Generated by Django 5.2.17 on 2026-09-08 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0003_appeal_category_appeal_close_kind_appeal_closed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appealevent',
            name='actor_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appealevent',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='appeals.appeal'),
        ),
        migrations.AddField(
            model_name='appealevent',
            name='assigned_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appealparticipant',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='appeals.appeal'),
        ),
        migrations.AddField(
            model_name='appealparticipant',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appealsession',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appeals.appeal'),
        ),
        migrations.AddConstraint(
            model_name='appealevent',
            constraint=models.UniqueConstraint(fields=('appeal', 'version'), name='appeal_event_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='appealevent',
            constraint=models.CheckConstraint(condition=models.Q(('actor_role__in', ['applicant', 'operator', 'expert', 'admin', 'system'])), name='event_valid_actor'),
        ),
        migrations.AddConstraint(
            model_name='appealparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True), ('role', 'responsible')), fields=('appeal',), name='appeal_one_responsible'),
        ),
        migrations.AddConstraint(
            model_name='appealparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('appeal', 'staff'), name='appeal_unique_active_participant'),
        ),
        migrations.AddConstraint(
            model_name='appealparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['responsible', 'coexecutor'])), name='participant_valid_role'),
        ),
    ]
