# Generated by Django 5.2.17 on 2026-09-08 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0005_preserve_history_and_audit_guard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='answer_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='answer_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='original_answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='appealevent',
            name='category_slug',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_version', models.PositiveIntegerField()),
                ('helped', models.BooleanField()),
                ('reason', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='appeals.appeal')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('appeal', 'answer_version'), name='feedback_one_per_answer'), models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='feedback_valid_rating')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(choices=[('applicant', 'Заявитель'), ('expert', 'Специалист')], max_length=16)),
                ('kind', models.CharField(choices=[('append', 'Сообщение'), ('reply', 'Ответ'), ('ask', 'Вопрос'), ('recommend', 'Рекомендации')], max_length=16)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField()),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='appeals.appeal')),
                ('author_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('appeal', 'version'), name='message_unique_version')],
            },
        ),
    ]
